"""
pytest.ini is used to configure pytest settings like markers, command line options,
and test behavior

"""
import pytest
[pytest]

addopts = -v --html=report.html
markers =
    smoke: smoke test cases
    regression: regression test cases
